### PR TITLE
Card: Jasper Stone, Raven

### PR DESCRIPTION
**Pull request by mmeldo**
This is a tricky one so please test is much as you can.
Also fixed Wendy's Teethkickers and updated shootout posse effects.

### CODE REVIEW

**Review by stopfstedt — CHANGES_REQUESTED** [review]
Jasper Stone checks out for me. 

However, I encountered a few issues with Raven:

1. Raven triggers twice in a round, not sure if that is correct tho. Once for winning the shootout on the location (+1 permanent bullet bonus), and then again during Sundown (+1 permanent bullet bonus). I don't think think that is correct, but will inquire in the discord.

raven

2. Raven prompts for a target to give a permanent bullet bonus, even if there is no eligible dudes in play (for example, all of my dudes already have a permanent bullet bonus). All of my dudes are highlighted, if i chose on with a permanent bullet bonus nothing happens and the effect fizzles (no additional bonus is granted), which is at least correct.

**Comment by mmeldo** [comment]
PR updated with fixes for reported issues.

**Comment by stopfstedt** [comment]
rules forum thread on Raven's effect: http://forums.pineboxentertainment.com/t/can-ravens-ability-grant-a-permanent-bullet-bonus-twice-per-round/4284

**Review by stopfstedt — APPROVED** [review]
LGTM.

**Pull request merged**
