### PR TITLE
Cannot move and boot effects, refactor and some cards

### PR DESCRIPTION
**Pull request by mmeldo**
Cards: Yagn's Mechanical Skeleton, Scoop Hound, Angelica Espinosa

I am aware this one will need some unit/integration tests, but I would like to do it as separate PR as this one is already quite big.

### CODE REVIEW

**Comment by AaronSchnabel** [comment]
I got the attached error when attempting to use Phantasm to move an unbooted dude from their home to TS
[movement error Phantasm.txt](https://github.com/townteki/townsquare/files/6272900/movement.error.Phantasm.txt)

**Comment by AaronSchnabel** [comment]
I tried to use Pistol Whip on a dude who had Yagn's attached, and it properly prevented the effect from taking place, but I was able to target the dude, and the game message said "drcthulhu2 uses Pistol Whip to send home booted " I don't know if there is a way to add a message on the cannot properties when it prevents something from happening, or if we should just prevent somebody from being targeted by an ability if they have a cannot effect for that ability.

**Comment by AaronSchnabel** [comment]
I attached Yagn's to Jarret Blake, and when I tried to use his shootout ability to move him into the posse, I got the needToBoot error again.
[need to boot error.txt](https://github.com/townteki/townsquare/files/6273168/need.to.boot.error.txt)

**Comment by AaronSchnabel** [comment]
Yagn's Mechanical Skeleton is broken somehow. If you attach it to a dude, everything works fine for that day. However, when you move into a new day, it makes you pay all of your money as upkeep (setting your stash to 0), and then it breaks something so that you cannot use the buttons to add ghost rock to your stash. This means you can't do any shoppin, etc. Using the /remove-from-game command to remove Yagn's and then moving to a new day does not reset this.

**Comment by mmeldo** [comment]
> Yagn's Mechanical Skeleton is broken somehow. If you attach it to a dude, everything works fine for that day. However, when you move into a new day, it makes you pay all of your money as upkeep (setting your stash to 0), and then it breaks something so that you cannot use the buttons to add ghost rock to your stash. This means you can't do any shoppin, etc. Using the /remove-from-game command to remove Yagn's and then moving to a new day does not reset this.

This was not problem with Yagn per se, but with the way upkeep has been determine. Yagn's bad luck was that it was first card other than dudes to have influence. Should be fixed.

**Comment by mmeldo** [comment]
All other reported bugs are fixed plus one new.

**Comment by mmeldo** [comment]
Had a short testing game with @janosikm and everything related to this PR went without problems.
@AaronSchnabel please verify the bug fixes for the problems you reported.

**Comment by AaronSchnabel** [comment]
Everything seems to be working A-OK to me. Good job!

**Pull request merged**
