### PR TITLE
Card: GT - Sunday Best

### PR DESCRIPTION
**Pull request by PesiTheWizard**
* Adding file for Sunday Best

* Marking Sunday Best

### CODE REVIEW

**Review by mmeldo — CHANGES_REQUESTED** [review]

**Comment by mmeldo** [comment]
Did not merge this one because the build is failing.

**Comment by PesiTheWizard** [comment]
So what was with the apostrophe-change anyway?

**Comment by PesiTheWizard** [comment]
This seems to just be made of fail. And I apparently forgot the boot cost. I think it's back to the drawing board.

**Comment by mmeldo** [comment]
> So what was with the apostrophe-change anyway?

with the normal apostrophes (' or "), everything in between them is considered a regular text.
but if you use \`, you can do a variable substitution by using `${variable}` in the text.

**Pull request closed without merging**
